/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: 1f86edab68431ee002f85a0292e079b0)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	RKG_CORS: "https://delwing.github.io";
	RKG_LIMIT_GLOSOW: "300";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
