/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: 0f94a5f3fba06a2026191d47c565cf30)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	RKG_CORS: "https://delwing.github.io";
	RKG_LIMIT_GLOSOW: "300";
	RKG_ADMIN: string;
	RKG_LIMIT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RKG_CORS" | "RKG_LIMIT_GLOSOW" | "RKG_ADMIN" | "RKG_LIMIT_SECRET">> {}
}
