/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: f9ed382a4e722c4e418662e90c270633)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	RKG_CORS: "https://delwing.github.io";
	RKG_LIMIT_GLOSOW: "300";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RKG_CORS" | "RKG_LIMIT_GLOSOW">> {}
}
